services:
    # pgvector Service:
    # running a PostgreSQL instance with the pgvector extension
    pgvector:
        image: pgvector/pgvector:0.8.0-pg17
        container_name: pgvector
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgvector_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            # - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - backend

networks:
    backend:

volumes:
    pgvector_data:
